esphome:
  name: garage-screen
  friendly_name: Garage Screen
  
substitutions:
  home_page: garage

packages:
  common: !include common.yaml
  device: !include devices/ESP32-2432S028R.yaml
  layout: !include layouts/garage.yaml
